### PR TITLE
Improve data pending states on dashboard [ch3118]

### PR DESCRIPTION
**Pull request by jacruzca**
Story Details: https://app.clubhouse.io/levels/story/3118/improve-data-pending-states-on-dashboard

First part of this feature. Show both lines in the given points and display a text in the middle. Text, lines color and height can be changed through parameters.

Second part will include the icon and the dashed line along with the x axis. I must create a separate example to avoid conflicts with the original repo and be able to update from upstream without too much trouble later.

Simulator Screen Shot - iPhone 11 - 2020-07-30 at 15 19 39

### CODE REVIEW

**Review by davidflinner — APPROVED** [review]

**Comment by davidflinner** [comment]
Are we switching to a completely new chart library?

**Comment by jacruzca** [comment]
No. This is the same library that the RN bridge is using under the hood for native iOS. None of what we're using now was offering the feature we need so we have to implement it natively, then in the bridge and finally in our app. Next up: Android native implementation

**Comment by jacruzca** [comment]
Closing in favor of https://github.com/levelshealth/Charts/pull/2

**Comment by jacruzca** [comment]
Reopening because the performance issues were not related to the last version of this library

**Pull request merged**
